openapi: 3.0.1
info:
  title: HealthCheck
  description: API Definition of HealthCheck
  version: 1.0.0
servers:
- url: http://localhost:8290/healthcheck
paths:
  /infobip:
    get:
      responses:
        default:
          description: Default response
  /tm:
    get:
      responses:
        default:
          description: Default response
  /database:
    get:
      responses:
        default:
          description: Default response
